from os import environ

USERNAME_RECEIVER = environ.get("MB_USERNAME_RECEIVER")
PASSWORD_RECEIVER = environ.get("MB_PASSWORD_RECEIVER")
USERNAME_SENDER = environ.get("MB_USERNAME_SENDER")
PASSWORD_SENDER = environ.get("MB_PASSWORD_SENDER")
